version: "3.9"

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: fairy
      POSTGRES_PASSWORD: fairy
      POSTGRES_DB: fairy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - minio

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  admin:
    build: ./admin-panel
    command: npm run dev -- --host
    volumes:
      - ./admin-panel:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data: