services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3002:3002"
    command: ["npm", "run", "dev"]
    environment:
      - API_URL=http://backend:4000/api
    depends_on:
      - backend

  crm:
    build:
      context: ./apps/crm
    ports:
      - "3001:3001"
    command: ["npm", "run", "dev"]
    environment:
      - API_URL=http://backend:4000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
    ports:
      - "4000:4000"
    command: ["npm", "run", "start:dev"]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=storybook
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storybook
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
