<script setup lang="ts">

useHead({
  title: "Create Turborepo (vue-nuxt:crm)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <div>1111
    <div>222</div>
  </div>
  <Button label="Verify1" />
</template>
